// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0CP81M6irPko-sbgnlMyWlA8J52Td5dg',
    appId: '1:953527711219:web:639e388a4e0a8802088e86',
    messagingSenderId: '953527711219',
    projectId: 'pet-zone-6a1ff',
    authDomain: 'pet-zone-6a1ff.firebaseapp.com',
    storageBucket: 'pet-zone-6a1ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNXIVKaZF0NhyyGSfgIQlmDxcGv-B5HgU',
    appId: '1:953527711219:android:2b6bd3177afa9c44088e86',
    messagingSenderId: '953527711219',
    projectId: 'pet-zone-6a1ff',
    storageBucket: 'pet-zone-6a1ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YdySHI4TtH2Fv-ob306iuKzLV5mYHGQ',
    appId: '1:953527711219:ios:766ab80a8f11e730088e86',
    messagingSenderId: '953527711219',
    projectId: 'pet-zone-6a1ff',
    storageBucket: 'pet-zone-6a1ff.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2YdySHI4TtH2Fv-ob306iuKzLV5mYHGQ',
    appId: '1:953527711219:ios:766ab80a8f11e730088e86',
    messagingSenderId: '953527711219',
    projectId: 'pet-zone-6a1ff',
    storageBucket: 'pet-zone-6a1ff.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemoApp',
  );
}
